services:
  - type: web
    name: shreekamla-backend
    env: python
    plan: free
    buildCommand: ""
    startCommand: waitress-serve --host=0.0.0.0 --port=8080 app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: shreekamla-db
          property: connectionString
      - key: ADMIN_1_EMAIL
        value: khalikarprasad@gmail.com
      - key: ADMIN_1_PASSWORD
        value: Prasad@58
      - key: ADMIN_2_EMAIL
        value: sunilkhalikar@gmail.com
      - key: ADMIN_2_PASSWORD
        value: Sunil@123
      - key: ADMIN_3_EMAIL
        value: manisha.khalikar@gmail.com
      - key: ADMIN_3_PASSWORD
        value: Manisha@123
